# Generated by Django 5.0.6 on 2024-06-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('count', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['count'],
            },
        ),
    ]
