# Generated by Django 5.0.6 on 2024-06-05 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shelter',
            new_name='QRcode',
        ),
    ]
